Vtr testing radar extractor comparison update
cheneyuwu/vtr_testing_radar pull request #14
Opened 2024-12-17 17:07 UTC by ElliotP-K

-Updated Boreas config files 
   - New detector parameters
   - Threshold values for ICP failure conditions (see[ VTR3 Update](https://github.com/utiasASRL/vtr3/pull/229))
   - New additions to so the configs work with code from the [VTR3 Gyro](https://github.com/utiasASRL/vtr3/commit/0d2c95c3c7fedfe089c35e3e58f0ccb073853c59) update
-Included code to save velocity results from odometry runs

2025-01-10 16:19 UTC, lisusdaniil commented on src/vtr_testing_radar/script/boreas_generate_odometry_result.py
> +
This is already implemented in the latest branch! Please remove the duplicate

2025-01-10 16:20 UTC, lisusdaniil requested changes
Please address few comments

2025-01-11 16:26 UTC, ElliotP-K commented on src/vtr_testing_radar/script/boreas_generate_odometry_result.py
> +
Removed

2025-01-14 16:13 UTC, lisusdaniil approved these changes

2025-01-14 16:13 UTC, merged